image: docker:20.10.16

stages:
  - stop-build-deploy

stop build deploy job:
  stage: stop-build-deploy
  script:
    - echo starting build-image job...
    - docker build -t study-center-api:v1.0.0 .
    - echo build-image job finished.

    - echo starting stop services job...
    - docker compose -f study-center-compose.yml down
    - echo stop-service job finished.

    - echo starting deploy job...
    - docker compose -f study-center-compose.yml up -d
    - echo deploy job finished.

    - docker rmi $(docker images -f "dangling=true" -q)
  only:
    - main
